#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ts=4 et
# Author: Juehai <juehai.gy@gmail.com>
import re
from datetime import datetime, timedelta
from pytz import timezone

SENSITIVE_TIMEZONE  = 'Pacific/Auckland'
SENSITIVE_TIME      = '00:00-06:00'

def check_sensitive():
    regex = re.compile(r'^(\d?\d:?\d\d)-(\d?\d:?\d\d)$')
    t1, t2 = regex.findall(SENSITIVE_TIME)[0]
    t1 = t1.replace(":", "")
    t2 = t2.replace(":", "")

    tz = timezone(SENSITIVE_TIMEZONE)
    now = datetime.now(tz)
    print now
    #print '%02i%02i' % (now.hour, now.minute)
    t3 = '%02i%02i' % (now.hour, now.minute)

    print t1, t2, t3

    if ( t1 < t2 ):
        if ( ( t1 <= t3 ) and ( t3 <= t2 ) ):
            raise Exception('matched')

    else:
        if ( ( t3 >= t1 ) or ( t3 <= t2 ) ):
            raise Exception('matched')

if __name__ == '__main__':
    check_sensitive()
