# System config
---
SMTP_HOST: 'smtp.gmail.com:587'
SMTP_USER: ''
SMTP_PASS: ''
DISPLAY_ME: 'EltonPostman'
SEND_TO: 
  - ''

# TradeMe Keys
CONSUMER_KEY:       ''
CONSUMER_SECRET:    ''
OAUTH_TOKEN:        ''
OAUTH_TOKEN_SECRET: ''

# Log level
LOG_LEVEL: 'DEBUG'

# Search config 
---
  .base:
    buy: 'All'
    category: ''
    condition: 'Used'
    date_from: ''
    expired: 'false'
    pay: 'All'
    photo_size: 'Gallery'
    return_metadata: 'false'
    page: '1'
    rows: '25'
    search_string: ''
    shipping_method: 'All'
    sort_order: 'ExpiryDesc'
    user_region: ''
  
  Trailers:
    .include: .base
    category: '0001-1259'
    
  Hobs & ovens:
    .include: .base
    category: '0004-0371-6881'
  
  Trailer_in_farming:
    .include: .base
    category: '0010-0395-'
    condition: 'All'
    search_string: 'trailer'

##  Rinnai_in_gas:
##    .include: .base
##    category: '0004-0370-0560-0933'
##    condition: 'All'
##    search_string: 'rinnai'

  gas:
    .include: .base
    category: '0010-0398'
    search_string: 'gas'
    user_region: '50'
  sheds:
    .include: .base
    category: '0004-0375-6873-9131-'
##  rheem laser:
##    .include: .base
##    category: ''
##    condition: 'All'
##    search_string: 'rheem laser'
##  rheem lazer:
##    .include: .base
##    category: ''   
##    condition: 'All'
##    search_string: 'rheem lazer'
  Freezers:
    .include: .base
    category: '0004-0371-0039-4182-'
  Hobs & ovens:
    .include: .base
    category: '0004-0371-6881-8282-'
